apiVersion: v1
kind: Pod
metadata:
  name: downward
spec:
  containers:
  - name: main
    image: busybox
    command: ["sleep", "9999"]
    resources:
      requests:
        cpu: 15m
        memory: 100Ki
      limits:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - name: downward
      mountPath: /etc/downward/
      readOnly: true
  volumes:
  - name: downward
    downwardAPI:
      items:
      - path: "podName"
        fieldRef:
        fieldPat  h: metadata.name
      - path: "podNamespace"
        fieldRef:
        fieldPa th: metadata.namespace
      - path: "labels"
        fieldRef:
        fieldPat  h: metadata.labels
      - path: "annotations"
        fieldRef:
        fieldPath:  metadata.annotations
      - path: "containerCpuRequestMilliCores"
        resourceFieldRef:
          containerName: main
          resource: requests.cpu
          divisor: 1m
      - path: "containerMemoryLimitBytes"
        resourceFieldRef:
          containerName: main
          resource: limits.memory
          divisor: 1