apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs
  labels:
  - app: kubia
spec:
  replicas: 5
  selector:
  - matchLabels:
      key: app
      operator: In
      value: kubia
  template:
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: \
              port: 80