apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: priveleged
spec:
  privileged: true
  runAsUser: 
    rule: RunAsAny
  fsGroup: 
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
  - "*"